### PR TITLE
Switch to use Alien::TidyHTML5, #8

### PR DESCRIPTION
**Pull request by robrwo**

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for the PR.  I don't want to make Alien::TidyHTML5 be a requirement to install HTML::Tidy5 if the user already has the lib installed.  What do we need to do to make it work with either one?

**Comment by robrwo** [comment]
The Alien is supposed to use the existing library if it's installed.

**Comment by petdance** [comment]
> The Alien is supposed to use the existing library if it's installed.

I get that.  I just don't want to have to involve Alien:: anything if it's not needed.

**Comment by robrwo** [comment]
Maybe run a separate test to look for the library, and if not, add
requirement for Alien?

**Comment by robrwo** [comment]
I have a prototype, though I think it needs an additional require.

I am also thinking that the code could be turned into an
ExtUtils::Alien::Maybe module since this may be useful for others.

**Comment by petdance** [comment]
I'd rather not pull in Devel::CheckLib.  Is it actually necessary?  HTML::Tidy5 doesn't use anything other than core modules.

**Comment by shlomif** [comment]
Hi!

Please apply this pull-req. I had to go to great lengths to fix installing HTML::Tidy5 on travis-ci, see https://github.com/shlomif/open-web-developer-tools/commit/620dbd51144a35f93b6cd09043d529a5e50dbab5 . I don't mind the checklib dependency, see https://shadow.cat/blog/matt-s-trout/but-i-cant-use-cpan/ .

**Comment by petdance** [comment]
I suspect there's a way for us to check for existing libtidy5 without having to drag in Devel::CheckLib.

**Comment by shlomif** [comment]
@robrwo : any idea?

**Comment by robrwo** [comment]
@shlomif @petdance Perhaps some code could be added to check if Alien::TidyHTML5 is installed, and adjust the installation paths. I think this would largely be copying what Alien does.

**Comment by shlomif** [comment]
@robrwo : I see. Good point. @petdance : they say that perfect is the enemy of good, and - in this case - the friend of a very bad situation. I don't see why this should not be merged as it is with the extra deps that should not be hard to install.

**Comment by Grinnz** [comment]
The point of Alien:: dists is that it abstracts the complication of checking whether a library exists or installing it for Perl's use. Optionally using an Alien:: module would seemingly not be useful, I would either use it (to fix the above issues) or leave it as is.

**Comment by petdance** [comment]
I'm not going to have HTML::Tidy5 require unnecessary modules.

If someone already has the tidy lib installed, then Alien::TidyHTML5 is unnecessary, as is Devel::CheckLib.

I'm open to solutions that do not install unnecessary modules.

**Pull request closed without merging**
